todo list
Nettar-Jr/TodoList-App pull request #3
Opened 2019-05-12 20:29 UTC by Nettar-Jr

...

2019-05-12 20:29 UTC, Nettar-Jr commented
...

2019-05-14 23:21 UTC, ngfizzy requested changes
Nice one. I love the little animation that you added. Spices things up a lil bit.

I also noticed that you cleaned up your code a lot more. Nice one.

Few feedback.

There are still quite a number of features yet to be implemented.
Let me know if you'd be needing a pairing session so we can figure this out. Nice job once again

2019-05-14 23:21 UTC, ngfizzy commented on todo.js
> +    document.getElementById('input').value;
fix indentation here. line 30 does not align well with  the if else statement above

2019-05-14 23:21 UTC, ngfizzy commented on todo.js
> +		todoItem.style.display = "none";
why are you hiding the element instead of actually removing the node?

2019-05-19 22:21 UTC, merged